#include "on_led.h"
void on_red1(){
	HAL_GPIO_WritePin(LED_GREEN1_GPIO_Port, LED_GREEN1_Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(LED_YEL1_GPIO_Port, LED_YEL1_Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(LED_RED1_GPIO_Port, LED_RED1_Pin, GPIO_PIN_RESET);
};
void on_yel1(){
	HAL_GPIO_WritePin(LED_GREEN1_GPIO_Port, LED_GREEN1_Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(LED_YEL1_GPIO_Port, LED_YEL1_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LED_RED1_GPIO_Port, LED_RED1_Pin, GPIO_PIN_SET);
};
void on_green1(){
	HAL_GPIO_WritePin(LED_GREEN1_GPIO_Port, LED_GREEN1_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LED_YEL1_GPIO_Port, LED_YEL1_Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(LED_RED1_GPIO_Port, LED_RED1_Pin, GPIO_PIN_SET);
};

void on_red2(){
	HAL_GPIO_WritePin(LED_GREEN2_GPIO_Port, LED_GREEN2_Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(LED_YEL2_GPIO_Port, LED_YEL2_Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(LED_RED2_GPIO_Port, LED_RED2_Pin, GPIO_PIN_RESET);
};
void on_yel2(){
	HAL_GPIO_WritePin(LED_GREEN2_GPIO_Port, LED_GREEN2_Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(LED_YEL2_GPIO_Port, LED_YEL2_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LED_RED2_GPIO_Port, LED_RED2_Pin, GPIO_PIN_SET);
};
void on_green2(){
	HAL_GPIO_WritePin(LED_GREEN2_GPIO_Port, LED_GREEN2_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LED_YEL2_GPIO_Port, LED_YEL2_Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(LED_RED2_GPIO_Port, LED_RED2_Pin, GPIO_PIN_SET);
};

void display7SEG_1 (int number){
	switch(number){
	case 0:
		HAL_GPIO_WritePin(A_7SEG_1_GPIO_Port, A_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(B_7SEG_1_GPIO_Port, B_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(C_7SEG_1_GPIO_Port, C_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(D_7SEG_1_GPIO_Port, D_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(E_7SEG_1_GPIO_Port, E_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(F_7SEG_1_GPIO_Port, F_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(G_7SEG_1_GPIO_Port, G_7SEG_1_Pin, GPIO_PIN_SET);
				break;
	case 1:
		HAL_GPIO_WritePin(A_7SEG_1_GPIO_Port, A_7SEG_1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(B_7SEG_1_GPIO_Port, B_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(C_7SEG_1_GPIO_Port, C_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(D_7SEG_1_GPIO_Port, D_7SEG_1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(E_7SEG_1_GPIO_Port, E_7SEG_1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(F_7SEG_1_GPIO_Port, F_7SEG_1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(G_7SEG_1_GPIO_Port, G_7SEG_1_Pin, GPIO_PIN_SET);
				break;
	case 2:
		HAL_GPIO_WritePin(A_7SEG_1_GPIO_Port, A_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(B_7SEG_1_GPIO_Port, B_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(C_7SEG_1_GPIO_Port, C_7SEG_1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(D_7SEG_1_GPIO_Port, D_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(E_7SEG_1_GPIO_Port, E_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(F_7SEG_1_GPIO_Port, F_7SEG_1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(G_7SEG_1_GPIO_Port, G_7SEG_1_Pin, GPIO_PIN_RESET);
				break;
	case 3:
		HAL_GPIO_WritePin(A_7SEG_1_GPIO_Port, A_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(B_7SEG_1_GPIO_Port, B_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(C_7SEG_1_GPIO_Port, C_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(D_7SEG_1_GPIO_Port, D_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(E_7SEG_1_GPIO_Port, E_7SEG_1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(F_7SEG_1_GPIO_Port, F_7SEG_1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(G_7SEG_1_GPIO_Port, G_7SEG_1_Pin, GPIO_PIN_RESET);
				break;
	case 4:
		HAL_GPIO_WritePin(A_7SEG_1_GPIO_Port, A_7SEG_1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(B_7SEG_1_GPIO_Port, B_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(C_7SEG_1_GPIO_Port, C_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(D_7SEG_1_GPIO_Port, D_7SEG_1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(E_7SEG_1_GPIO_Port, E_7SEG_1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(F_7SEG_1_GPIO_Port, F_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(G_7SEG_1_GPIO_Port, G_7SEG_1_Pin, GPIO_PIN_RESET);
				break;
	case 5:
		HAL_GPIO_WritePin(A_7SEG_1_GPIO_Port, A_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(B_7SEG_1_GPIO_Port, B_7SEG_1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(C_7SEG_1_GPIO_Port, C_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(D_7SEG_1_GPIO_Port, D_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(E_7SEG_1_GPIO_Port, E_7SEG_1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(F_7SEG_1_GPIO_Port, F_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(G_7SEG_1_GPIO_Port, G_7SEG_1_Pin, GPIO_PIN_RESET);
				break;
	case 6:
		HAL_GPIO_WritePin(A_7SEG_1_GPIO_Port, A_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(B_7SEG_1_GPIO_Port, B_7SEG_1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(C_7SEG_1_GPIO_Port, C_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(D_7SEG_1_GPIO_Port, D_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(E_7SEG_1_GPIO_Port, E_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(F_7SEG_1_GPIO_Port, F_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(G_7SEG_1_GPIO_Port, G_7SEG_1_Pin, GPIO_PIN_RESET);
				break;
	case 7:
		HAL_GPIO_WritePin(A_7SEG_1_GPIO_Port, A_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(B_7SEG_1_GPIO_Port, B_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(C_7SEG_1_GPIO_Port, C_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(D_7SEG_1_GPIO_Port, D_7SEG_1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(E_7SEG_1_GPIO_Port, E_7SEG_1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(F_7SEG_1_GPIO_Port, F_7SEG_1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(G_7SEG_1_GPIO_Port, G_7SEG_1_Pin, GPIO_PIN_SET);
				break;
	case 8:
		HAL_GPIO_WritePin(A_7SEG_1_GPIO_Port, A_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(B_7SEG_1_GPIO_Port, B_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(C_7SEG_1_GPIO_Port, C_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(D_7SEG_1_GPIO_Port, D_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(E_7SEG_1_GPIO_Port, E_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(F_7SEG_1_GPIO_Port, F_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(G_7SEG_1_GPIO_Port, G_7SEG_1_Pin, GPIO_PIN_RESET);
				break;
	case 9:
		HAL_GPIO_WritePin(A_7SEG_1_GPIO_Port, A_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(B_7SEG_1_GPIO_Port, B_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(C_7SEG_1_GPIO_Port, C_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(D_7SEG_1_GPIO_Port, D_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(E_7SEG_1_GPIO_Port, E_7SEG_1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(F_7SEG_1_GPIO_Port, F_7SEG_1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(G_7SEG_1_GPIO_Port, G_7SEG_1_Pin, GPIO_PIN_RESET);
				break;
	default:
		break;
	}
};

void display7SEG_2 (int number){
	switch(number){
	case 0:
		HAL_GPIO_WritePin(A_7SEG_2_GPIO_Port, A_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(B_7SEG_2_GPIO_Port, B_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(C_7SEG_2_GPIO_Port, C_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(D_7SEG_2_GPIO_Port, D_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(E_7SEG_2_GPIO_Port, E_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(F_7SEG_2_GPIO_Port, F_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(G_7SEG_2_GPIO_Port, G_7SEG_2_Pin, GPIO_PIN_SET);
				break;
	case 1:
		HAL_GPIO_WritePin(A_7SEG_2_GPIO_Port, A_7SEG_2_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(B_7SEG_2_GPIO_Port, B_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(C_7SEG_2_GPIO_Port, C_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(D_7SEG_2_GPIO_Port, D_7SEG_2_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(E_7SEG_2_GPIO_Port, E_7SEG_2_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(F_7SEG_2_GPIO_Port, F_7SEG_2_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(G_7SEG_2_GPIO_Port, G_7SEG_2_Pin, GPIO_PIN_SET);
				break;
	case 2:
		HAL_GPIO_WritePin(A_7SEG_2_GPIO_Port, A_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(B_7SEG_2_GPIO_Port, B_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(C_7SEG_2_GPIO_Port, C_7SEG_2_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(D_7SEG_2_GPIO_Port, D_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(E_7SEG_2_GPIO_Port, E_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(F_7SEG_2_GPIO_Port, F_7SEG_2_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(G_7SEG_2_GPIO_Port, G_7SEG_2_Pin, GPIO_PIN_RESET);
				break;
	case 3:
		HAL_GPIO_WritePin(A_7SEG_2_GPIO_Port, A_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(B_7SEG_2_GPIO_Port, B_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(C_7SEG_2_GPIO_Port, C_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(D_7SEG_2_GPIO_Port, D_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(E_7SEG_2_GPIO_Port, E_7SEG_2_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(F_7SEG_2_GPIO_Port, F_7SEG_2_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(G_7SEG_2_GPIO_Port, G_7SEG_2_Pin, GPIO_PIN_RESET);
				break;
	case 4:
		HAL_GPIO_WritePin(A_7SEG_2_GPIO_Port, A_7SEG_2_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(B_7SEG_2_GPIO_Port, B_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(C_7SEG_2_GPIO_Port, C_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(D_7SEG_2_GPIO_Port, D_7SEG_2_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(E_7SEG_2_GPIO_Port, E_7SEG_2_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(F_7SEG_2_GPIO_Port, F_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(G_7SEG_2_GPIO_Port, G_7SEG_2_Pin, GPIO_PIN_RESET);
				break;
	case 5:
		HAL_GPIO_WritePin(A_7SEG_2_GPIO_Port, A_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(B_7SEG_2_GPIO_Port, B_7SEG_2_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(C_7SEG_2_GPIO_Port, C_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(D_7SEG_2_GPIO_Port, D_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(E_7SEG_2_GPIO_Port, E_7SEG_2_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(F_7SEG_2_GPIO_Port, F_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(G_7SEG_2_GPIO_Port, G_7SEG_2_Pin, GPIO_PIN_RESET);
				break;
	case 6:
		HAL_GPIO_WritePin(A_7SEG_2_GPIO_Port, A_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(B_7SEG_2_GPIO_Port, B_7SEG_2_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(C_7SEG_2_GPIO_Port, C_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(D_7SEG_2_GPIO_Port, D_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(E_7SEG_2_GPIO_Port, E_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(F_7SEG_2_GPIO_Port, F_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(G_7SEG_2_GPIO_Port, G_7SEG_2_Pin, GPIO_PIN_RESET);
				break;
	case 7:
		HAL_GPIO_WritePin(A_7SEG_2_GPIO_Port, A_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(B_7SEG_2_GPIO_Port, B_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(C_7SEG_2_GPIO_Port, C_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(D_7SEG_2_GPIO_Port, D_7SEG_2_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(E_7SEG_2_GPIO_Port, E_7SEG_2_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(F_7SEG_2_GPIO_Port, F_7SEG_2_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(G_7SEG_2_GPIO_Port, G_7SEG_2_Pin, GPIO_PIN_SET);
				break;
	case 8:
		HAL_GPIO_WritePin(A_7SEG_2_GPIO_Port, A_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(B_7SEG_2_GPIO_Port, B_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(C_7SEG_2_GPIO_Port, C_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(D_7SEG_2_GPIO_Port, D_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(E_7SEG_2_GPIO_Port, E_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(F_7SEG_2_GPIO_Port, F_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(G_7SEG_2_GPIO_Port, G_7SEG_2_Pin, GPIO_PIN_RESET);
				break;
	case 9:
		HAL_GPIO_WritePin(A_7SEG_2_GPIO_Port, A_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(B_7SEG_2_GPIO_Port, B_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(C_7SEG_2_GPIO_Port, C_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(D_7SEG_2_GPIO_Port, D_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(E_7SEG_2_GPIO_Port, E_7SEG_2_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(F_7SEG_2_GPIO_Port, F_7SEG_2_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(G_7SEG_2_GPIO_Port, G_7SEG_2_Pin, GPIO_PIN_RESET);
				break;
	default:
		break;
	}
};
